version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: weekbook
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      BOOTSTRAP: false
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data: