version: '3.8'

services:
  postgres-service:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: weekbook
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-service:
    build: .
    image: backend:latest
    container_name: backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    volumes:
      - ./media:/media
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data: